# Hermetic build spike - using public RHEL base image instead of AIPCC
BASE_IMAGE=registry.redhat.io/rhel9/python-312:9.6-1762373758
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=odh
LABEL_COMPONENT=odh-workbench-jupyter-testing-cpu-py312-ubi9
PRODUCT=odh
RELEASE=spike
