ARG TARGETARCH

#########################
# configuration args    #
#########################
ARG BASE_IMAGE

####################
# cuda-base        #
####################
FROM ${BASE_IMAGE} AS cuda-base

WORKDIR /opt/app-root/bin

# hadolint ignore=DL3002
USER 0

RUN rpm --import /cachi2/output/deps/generic/RPM-GPG-KEY-CentOS-Official || true
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

COPY prefetch-input/odh/rpms.lock.yaml /dev/null
COPY prefetch-input/rhds/rpms.lock.yaml /dev/null

RUN --mount=type=bind,source=base-images/utils/dnf-helper.sh,target=/utils/dnf-helper.sh,ro \
    /utils/dnf-helper.sh install perl mesa-libGL skopeo compat-openssl11 openshift-clients libxcrypt-compat

RUN pip install --no-cache-dir --no-index --find-links /cachi2/output/deps/pip "micropipenv[toml]" "uv"

USER 1001

#########################
# cuda-runtime-pytorch  #
#########################
FROM cuda-base AS cuda-runtime-pytorch

ARG PYTORCH_SOURCE_CODE=runtimes/pytorch+llmcompressor/ubi9-python-3.12
ARG PYLOCK_FLAVOR

ARG LABEL_NAME=""
ARG LABEL_SUMMARY=""
ARG LABEL_DESCRIPTION=""
ARG LABEL_DISPLAY_NAME=""
ARG LABEL_K8S_DESCRIPTION=""
ARG LABEL_COM_REDHAT_COMPONENT=""
ARG LABEL_COM_REDHAT_LICENSE_TERMS=""
ARG LABEL_AUTHORITATIVE_SOURCE_URL=""
ARG LABEL_BUILD_COMMIT_REF=""
ARG LABEL_BUILD_SOURCE_LOCATION=""
ARG LABEL_BUILD_IMAGE=""

LABEL name="${LABEL_NAME}" \
      summary="${LABEL_SUMMARY}" \
      description="${LABEL_DESCRIPTION}" \
      io.k8s.display-name="${LABEL_DISPLAY_NAME}" \
      io.k8s.description="${LABEL_K8S_DESCRIPTION}" \
      com.redhat.component="${LABEL_COM_REDHAT_COMPONENT}" \
      com.redhat.license_terms="${LABEL_COM_REDHAT_LICENSE_TERMS}" \
      authoritative-source-url="${LABEL_AUTHORITATIVE_SOURCE_URL}" \
      io.openshift.build.commit.ref="${LABEL_BUILD_COMMIT_REF}" \
      io.openshift.build.source-location="${LABEL_BUILD_SOURCE_LOCATION}" \
      io.openshift.build.image="${LABEL_BUILD_IMAGE}"

WORKDIR /opt/app-root/bin

COPY --chown=1001:0 ${PYTORCH_SOURCE_CODE}/uv.lock.d/pylock.${PYLOCK_FLAVOR}.toml ./pylock.toml
COPY --chown=1001:0 ${PYTORCH_SOURCE_CODE}/requirements.${PYLOCK_FLAVOR}.txt ./requirements.txt
COPY --chown=1001:0 ${PYTORCH_SOURCE_CODE}/utils ./utils/

USER 0

COPY --chown=1001:0 prefetch-input/elyra-v4.3.1/elyra/kfp/bootstrapper.py /opt/app-root/bin/utils/bootstrapper.py

ENV ELYRA_INSTALL_PACKAGES="false"

RUN /bin/bash <<'EOF'
set -Eeuxo pipefail

echo "Installing software and packages"
UV_NO_CACHE=true UV_LINK_MODE=copy UV_PREVIEW_FEATURES=pylock uv pip install --no-index \
    --strict --no-deps --no-config --no-progress \
    --compile-bytecode --index-strategy=unsafe-best-match \
    --no-verify-hashes \
    --find-links /cachi2/output/deps/pip \
    --requirements=./requirements.txt

chmod -R g+w /opt/app-root/lib/python3.12/site-packages
fix-permissions /opt/app-root -P
EOF

USER 1001

WORKDIR /opt/app-root/src
