FROM quay.io/centos/centos:stream9

RUN /bin/bash <<'EOF'
set -Eeuxo pipefail
export OPENBLAS_VERSION=${OPENBLAS_VERSION:-0.3.30}
cd /root
curl -L https://github.com/OpenMathLib/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/OpenBLAS-${OPENBLAS_VERSION}.tar.gz | tar xz
mv OpenBLAS-${OPENBLAS_VERSION}/ OpenBLAS/
EOF

RUN --mount=type=cache,target=/var/cache/dnf,sharing=locked,id=notebooks-dnf /bin/bash <<'EOF'
set -Eeuxo pipefail
dnf install -y epel-release
dnf install -y ccache make gcc
EOF

RUN --mount=type=cache,target=/var/cache/dnf,sharing=locked,id=notebooks-dnf /bin/bash <<'EOF'
set -Eeuxo pipefail
# this is clang variant of the library, for zig cc
dnf install -y libomp-devel
EOF

RUN --mount=type=cache,target=/root/.cache/zig,sharing=locked,id=notebooks-zig \
    --mount=type=cache,target=/ccache \
    /bin/bash <<'EOF'
set -Eeuxo pipefail
#export CC="ccache ${CC}"
#export CXX="ccache ${CXX}"
export CCACHE_DIR=/ccache
ccache -s

cd /root/OpenBLAS/
export MAX_JOBS=${MAX_JOBS:-$(nproc)}
make -j${MAX_JOBS} TARGET=POWER9 BINARY=64 USE_OPENMP=1 USE_THREAD=1 NUM_THREADS=120 DYNAMIC_ARCH=1 INTERFACE64=0
make PREFIX=/usr/local install NO_STATIC=1
EOF
