# https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#resource-not-accessible

### GET request to example server
POST https://api.github.com/repos/opendatahub-io/notebooks/issues/1857/labels
Authorization: Bearer <token>
Content-Type: application/json

###
