---
# pinact configuration
# https://github.com/suzuki-shunsuke/pinact
version: 3

# Two spaces before # to satisfy yamllint's "comments" rule
# (too few spaces before comment: expected 2)
separator: "  # "
