exclude:
  - "./tests/**"
  - "./scripts/buildinputs/**"
  - "./scripts/check-payload/**"
  - "./scripts/validate-imagestreams/**"
  - "./ci/dockerfile/**"
  - "./docs/go.mod"
  - "./jupyter/utils/addons/**"
  - "./example/**"
  - "./uv.lock"
  - "./.artifacts/**"
  - "./tmp/**"
  - "./bin/**"
