---
exclude:
  - "./uv.lock"
  - "./pyproject.toml"

  - "./ci/dockerfile/**"
  - "./docs/**"
  - "./example/**"
  - "./scripts/buildinputs/**"
  - "./scripts/check-payload/**"
  - "./scripts/validate-imagestreams/**"
  - "./tests/**"

  - "./jupyter/utils/addons/**"

  - "./.artifacts/**"
  - "./tmp/**"
  - "./bin/**"
