INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9-test/simple/
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest
PYLOCK_FLAVOR=cpu
LABEL_NAME=odh-notebook-code-server-ubi9-python-3.12
LABEL_SUMMARY=code-server image with python 3.12 based on UBI 9
LABEL_DESCRIPTION=code-server image with python 3.12 based on UBI9
LABEL_DISPLAY_NAME=code-server image with python 3.12 based on UBI9
LABEL_K8S_DESCRIPTION=code-server image with python 3.12 based on UBI9
LABEL_COM_REDHAT_COMPONENT=
LABEL_COM_REDHAT_LICENSE_TERMS=
LABEL_AUTHORITATIVE_SOURCE_URL=https://github.com/opendatahub-io/notebooks
LABEL_BUILD_COMMIT_REF=main
LABEL_BUILD_SOURCE_LOCATION=https://github.com/opendatahub-io/notebooks/tree/main/codeserver/ubi9-python-3.12
LABEL_BUILD_IMAGE=quay.io/opendatahub/workbench-images:codeserver-ubi9-python-3.12
