FROM registry.fedoraproject.org/fedora:44
RUN dnf install -y --quiet python3 python3-pip python3-createrepo_c git-core && \
    pip install --quiet --root-user-action=ignore \
      "hermeto @ git+https://github.com/hermetoproject/hermeto@0.46.2" && \
    dnf clean all
ENTRYPOINT ["hermeto"]
