# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v12.9@sha256:76e925bd478e9abcd5b40004fff58fa30f08daea1835a49cc024fc8d16b400e0
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-tensorflow-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.6
