# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s@sha256:b3b2d35032404b96a271f37986e00ccef282fa5edc4a2c2ba67b2736aeaad621
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-tensorflow-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.5
