# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.8:3.6.0-ea.2-1788563091@sha256:db63bf32c135a0b99943e4a3b03303603ab62ce93c193865820c86a18685db6d
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-tensorflow-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
