# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.6.0-ea.1-1785868193@sha256:e484883c7e78df9fab2cf3df9a16cb5dbba10c4c1cdbb9476c88ed58982272de
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-tensorflow-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
