INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-ea.1-1778849576
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-minimal-cpu-py312-rhel9
PRODUCT=rhoai
