# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu-el9.8:3.6.0-ea.1-1787611401@sha256:a22b7adc5eed164d61d616280b217adfd4d1d2ee1b08697640ab2a7e49595087
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-minimal-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
