# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu-el9.8:3.6.0-ea.2-1789501857@sha256:ee0d1768509216409f08119938fe0603bc2bd2c10b719828f71b7d7730a9aa41
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-minimal-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
