"""Unit tests for pylocks_generator exclude-newer helpers."""

from __future__ import annotations

import os
import re
import tomllib
from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import Mock

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[3]
# _SCRIPTS = _REPO_ROOT / "scripts"
# if str(_SCRIPTS) not in sys.path:
#     sys.path.insert(0, str(_SCRIPTS))

import scripts.index_url_resolver as resolver  # ruff: ignore[module-import-not-at-top-of-file]
import scripts.pylocks_generator as pg  # ruff: ignore[module-import-not-at-top-of-file]


@pytest.fixture
def repo_root() -> Path:
    return _REPO_ROOT


def test_detect_flavors_uses_konflux_dockerfiles(repo_root: Path) -> None:
    flavors = pg.detect_flavors(repo_root / "jupyter" / "minimal" / "ubi9-python-3.12")
    assert flavors == {"cpu", "cuda", "rocm"}


def test_detect_flavors_empty_when_no_konflux_dockerfiles(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    (project_dir / "Dockerfile.cpu").write_text("FROM scratch\n", encoding="utf-8")
    assert pg.detect_flavors(project_dir) == set()


def test_discover_all_image_project_dirs_skips_unversioned_pyproject(repo_root: Path) -> None:
    leaked = [d for d in pg.discover_all_image_project_dirs() if d.name == "py-pyproject-toml"]
    assert leaked == [], f"Copilot fixtures must not be lock targets: {leaked}"


def test_utc_now_iso_format() -> None:
    s = pg.utc_now_iso()
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.999999Z", s), s


def test_end_of_second_cutoff() -> None:
    assert pg._end_of_second_cutoff(datetime(2026, 8, 20, 1, 13, 38, tzinfo=UTC)) == ("2026-08-20T01:13:38.999999Z")
    # fractional seconds collapse to the end of the same second
    assert pg._end_of_second_cutoff(datetime(2026, 8, 20, 1, 13, 38, 123456, tzinfo=UTC)) == (
        "2026-08-20T01:13:38.999999Z"
    )
    # naive datetimes are treated as UTC
    assert pg._end_of_second_cutoff(datetime(2026, 8, 20, 1, 13, 38)) == "2026-08-20T01:13:38.999999Z"


def test_parse_exclude_newer_equals_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --exclude-newer=2025-06-01T12:30:45Z --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45Z"


def test_parse_exclude_newer_space_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --exclude-newer 2025-06-01T12:30:45Z --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45Z"


def test_parse_exclude_newer_offset_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile --exclude-newer=2025-06-01T12:30:45+00:00 x\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45+00:00"


def test_parse_exclude_newer_missing(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) is None


def test_parse_exclude_newer_missing_file(tmp_path: Path) -> None:
    assert pg.parse_exclude_newer_from_lockfile(tmp_path / "nope.toml") is None


def test_parse_max_upload_time_from_wheels(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        'lock-version = "1.0"\n'
        "[[packages]]\n"
        'name = "a"\n'
        "wheels = [\n"
        '  { url = "https://example.com/a-1.whl", upload-time = 2025-06-01T12:30:45Z },\n'
        '  { url = "https://example.com/a-2.whl", upload-time = 2025-06-02T08:00:00Z },\n'
        "]\n"
        "[[packages]]\n"
        'name = "b"\n'
        'sdist = { url = "https://example.com/b.tar.gz", upload-time = 2025-06-03T01:02:03Z }\n',
        encoding="utf-8",
    )
    assert pg.parse_max_upload_time_from_lockfile(p) == "2025-06-03T01:02:03.999999Z"


def test_parse_max_upload_time_preserves_fractional_seconds(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        'lock-version = "1.0"\n'
        "[[packages]]\n"
        'name = "a"\n'
        'wheels = [{ url = "https://example.com/a.whl", upload-time = 2025-06-01T12:30:45.100000Z }]\n'
        "[[packages]]\n"
        'name = "b"\n'
        'sdist = { url = "https://example.com/b.tar.gz", upload-time = 2025-06-03T01:02:03.456789Z }\n',
        encoding="utf-8",
    )
    assert pg.parse_max_upload_time_from_lockfile(p) == "2025-06-03T01:02:03.999999Z"


def test_parse_max_upload_time_missing(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text('lock-version = "1.0"\n[[packages]]\nname = "a"\n', encoding="utf-8")
    assert pg.parse_max_upload_time_from_lockfile(p) is None


def test_compile_command_for_lock_header() -> None:
    cmd = [
        "/repo/uv",
        "pip",
        "compile",
        "pyproject.toml",
        "--quiet",
        "--exclude-newer=2025-06-01T12:30:45Z",
        "--default-index=https://pypi.org/simple",
    ]
    header = pg.compile_command_for_lock_header(cmd)
    assert header == "uv pip compile pyproject.toml --default-index=https://pypi.org/simple"
    assert "--exclude-newer" not in header
    assert "--quiet" not in header


def test_strip_exclude_newer_from_export_lock_header(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv export --python=3.12 --format pylock.toml --output-file pylock.toml --no-annotate"
        " --emit-index-url --exclude-newer=2026-09-01T14:47:32Z --default-index=https://pypi.org/simple\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    cmd = [
        "/repo/uv",
        "export",
        "--python=3.12",
        "--format",
        "pylock.toml",
        "--output-file",
        "pylock.toml",
        "--no-annotate",
        "--emit-index-url",
        "--exclude-newer=2026-09-01T14:47:32Z",
        "--quiet",
        "--default-index=https://pypi.org/simple",
    ]
    pg._strip_exclude_newer_from_lock_header(p, cmd)
    lines = p.read_text(encoding="utf-8").splitlines()
    assert lines[1] == (
        "#    uv export --python=3.12 --format pylock.toml --output-file pylock.toml --no-annotate"
        " --emit-index-url --default-index=https://pypi.org/simple"
    )
    assert "--exclude-newer" not in lines[1]
    assert lines[2] == 'lock-version = "1.0"'


def test_strip_exclude_newer_from_lock_header_missing_file(tmp_path: Path) -> None:
    pg._strip_exclude_newer_from_lock_header(tmp_path / "nope.toml", ["uv", "export"])


def test_parse_exclude_newer_real_cpu_lock_header(repo_root: Path) -> None:
    sample = repo_root / "jupyter" / "datascience" / "ubi9-python-3.12" / "uv.lock.d" / "pylock.cpu.toml"
    if not sample.is_file():
        pytest.skip("sample lockfile not present")
    parsed = pg.parse_max_upload_time_from_lockfile(sample)
    assert parsed is not None


def test_resolve_exclude_newer_live_mode(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text("# no exclude\n", encoding="utf-8")
    assert pg.resolve_exclude_newer(p, ci_check=False, live_timestamp="2020-01-01T00:00:00Z") == (
        "2020-01-01T00:00:00Z"
    )


def test_resolve_exclude_newer_ci_parsed(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        'lock-version = "1.0"\n'
        "[[packages]]\n"
        'name = "a"\n'
        'wheels = [{ url = "https://example.com/a.whl", upload-time = 2099-01-01T00:00:00Z }]\n',
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == (
        "2099-01-01T00:00:00.999999Z"
    )


def test_resolve_exclude_newer_ci_end_of_second_for_whole_second_upload_time(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        'lock-version = "1.0"\n'
        "[[packages]]\n"
        'name = "llmcompressor"\n'
        'wheels = [{ url = "https://example.com/llmcompressor.whl", upload-time = 2026-08-20T01:13:38Z }]\n',
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == (
        "2026-08-20T01:13:38.999999Z"
    )


def test_resolve_exclude_newer_ci_preserves_fractional_seconds(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        'lock-version = "1.0"\n'
        "[[packages]]\n"
        'name = "a"\n'
        'wheels = [{ url = "https://example.com/a.whl", upload-time = 2099-01-01T00:00:00.123456Z }]\n',
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == (
        "2099-01-01T00:00:00.999999Z"
    )


def test_resolve_exclude_newer_ci_fallback(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "#    uv pip compile pyproject.toml --quiet\n",
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == ("2020-01-01T00:00:00Z")


class TestEnsureJsonFormatParam:
    def test_bare_url(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/") == ("https://example.com/simple/?format=json")

    def test_no_trailing_slash(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple") == ("https://example.com/simple?format=json")

    def test_already_has_format_json(self) -> None:
        url = "https://example.com/simple/?format=json"
        assert pg.ensure_json_format_param(url) == url

    def test_overwrites_non_json_format(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/?format=html") == (
            "https://example.com/simple/?format=json"
        )

    def test_other_query_params(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/?other=1") == (
            "https://example.com/simple/?other=1&format=json"
        )

    def test_real_aipcc_url(self) -> None:
        url = "https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.4/cpu-ubi9/simple/"
        result = pg.ensure_json_format_param(url)
        assert result == url + "?format=json"
        assert pg.ensure_json_format_param(result) == result


def test_get_index_flags_uses_konflux_conf(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "project"
    build_args = project_dir / "build-args"
    build_args.mkdir(parents=True)
    (build_args / "konflux.cpu.conf").write_text(
        "BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-ea.2-1778762488\nPYLOCK_FLAVOR=cpu\nPRODUCT=rhoai\n",
        encoding="utf-8",
    )
    label_url = "https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9/simple/"
    monkeypatch.setattr(
        resolver,
        "inspect_base_image_index_url",
        lambda _base_image: label_url,
    )
    monkeypatch.setattr(
        resolver,
        "index_url_exists",
        lambda url: url == label_url,
    )

    flags = pg.get_index_flags(project_dir, "cpu", pg.LogBuffer())

    assert flags == [
        "--default-index=https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9/simple/?format=json",
    ]


def test_get_index_flags_falls_back_to_test_index(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "project"
    build_args = project_dir / "build-args"
    build_args.mkdir(parents=True)
    (build_args / "konflux.cpu.conf").write_text(
        "BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-ea.2-1778762488\nPYLOCK_FLAVOR=cpu\nPRODUCT=rhoai\n",
        encoding="utf-8",
    )
    label_url = "https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9/simple/"
    monkeypatch.setattr(
        resolver,
        "inspect_base_image_index_url",
        lambda _base_image: label_url,
    )
    monkeypatch.setattr(
        resolver,
        "index_url_exists",
        lambda url: url.endswith("/cpu-ubi9-test/simple/"),
    )

    flags = pg.get_index_flags(project_dir, "cpu", pg.LogBuffer())

    assert flags == [
        "--default-index=https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9-test/simple/?format=json",
    ]


def test_run_lock_logs_index_url(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()

    log = pg.LogBuffer()
    completed = pg.subprocess.CompletedProcess(args=["uv"], returncode=0, stdout="", stderr="")

    def fake_run(*args, **kwargs):
        return completed

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    success = pg.run_lock(
        project_dir,
        "cpu",
        ["--default-index=https://example.invalid/simple/?format=json"],
        pg.IndexMode.rh_index,
        "3.12",
        False,
        False,
        "2026-05-18T00:00:00Z",
        log,
    )

    assert success is True
    assert any("Lock INDEX_URL: https://example.invalid/simple/?format=json" in line for line in log._lines)


def test_generate_requirements_txt_falls_back_to_pylock_header_when_index_resolution_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    log = pg.LogBuffer()
    captured_cmd: list[str] = []

    def fake_run(cmd, **kwargs):
        captured_cmd[:] = cmd
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg, "resolve_rh_index_config", lambda *args, **kwargs: None)
    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    success = pg.generate_requirements_txt(project_dir, "cpu", log)

    assert success is True, "generate_requirements_txt should succeed when index resolution fails"
    assert captured_cmd == [
        pg.sys.executable,
        str(pg.PYLOCK_TO_REQUIREMENTS),
        str(project_dir / "uv.lock.d" / "pylock.cpu.toml"),
        str(project_dir / "requirements.cpu.txt"),
    ], f"unexpected pylock-to-requirements command: {captured_cmd}"


def test_generate_requirements_txt_public_index_uses_root_pylock_without_index_url(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    log = pg.LogBuffer()
    captured_cmd: list[str] = []

    def fake_run(cmd, **kwargs):
        captured_cmd[:] = cmd
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    def fail_rh_index(*args, **kwargs):
        raise AssertionError("public-index conversion must not resolve an RH index URL")

    monkeypatch.setattr(pg, "resolve_rh_index_config", fail_rh_index)
    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    success = pg.generate_requirements_txt(project_dir, "cpu", log, public_index=True)

    assert success is True, "public-index generate_requirements_txt should succeed"
    assert captured_cmd == [
        pg.sys.executable,
        str(pg.PYLOCK_TO_REQUIREMENTS),
        "--sdist-hashes",
        "prefer",
        str(project_dir / "pylock.toml"),
        str(project_dir / "requirements.cpu.txt"),
    ], f"unexpected public-index pylock-to-requirements command: {captured_cmd}"


def test_effective_index_mode_without_uv_lock_d_is_public_index(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    assert pg.effective_index_mode(project_dir, pg.IndexMode.auto) == pg.IndexMode.public_index, (
        "auto mode without uv.lock.d/ should be public-index"
    )


def test_effective_index_mode_with_uv_lock_d_is_rh_index(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    (project_dir / "uv.lock.d").mkdir(parents=True)
    assert pg.effective_index_mode(project_dir, pg.IndexMode.auto) == pg.IndexMode.rh_index, (
        "auto mode with uv.lock.d/ should be rh-index"
    )


def test_effective_index_mode_honors_explicit_mode(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    (project_dir / "uv.lock.d").mkdir(parents=True)
    assert pg.effective_index_mode(project_dir, pg.IndexMode.public_index) == pg.IndexMode.public_index, (
        "explicit public-index must win even when uv.lock.d/ exists"
    )


def _public_index_project(tmp_path: Path) -> Path:
    project_dir = tmp_path / "jupyter" / "baseline" / "ubi9-python-3.12"
    project_dir.mkdir(parents=True)
    (project_dir / "Dockerfile.konflux.cpu").write_text("FROM scratch\n", encoding="utf-8")
    (project_dir / "pyproject.toml").write_text(
        '[project]\nname = "test"\nversion = "0.1.0"\nrequires-python = "==3.12.*"\n',
        encoding="utf-8",
    )
    (project_dir / "pylock.toml").write_text('lock-version = "1.0"\n', encoding="utf-8")
    return project_dir


def test_process_directory_public_index_requirements_only(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = _public_index_project(tmp_path)
    captured_cmd: list[str] = []

    def fake_run(cmd, **kwargs):
        captured_cmd[:] = cmd
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    _path, success, _log = pg.process_directory(
        project_dir,
        pg.IndexMode.public_index,
        False,
        False,
        "2026-01-01T00:00:00Z",
        requirements_only=True,
    )

    assert success is True, "public-index --requirements-only should succeed when pylock.toml exists"
    assert captured_cmd == [
        pg.sys.executable,
        str(pg.PYLOCK_TO_REQUIREMENTS),
        "--sdist-hashes",
        "prefer",
        str(project_dir / "pylock.toml"),
        str(project_dir / "requirements.cpu.txt"),
    ], f"unexpected --requirements-only command: {captured_cmd}"


def test_process_directory_public_index_generates_requirements_after_lock(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = _public_index_project(tmp_path)
    cmds: list[list[str]] = []

    def fake_run(cmd, **kwargs):
        cmds.append(list(cmd))
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    _path, success, _log = pg.process_directory(
        project_dir,
        pg.IndexMode.public_index,
        False,
        False,
        "2026-01-01T00:00:00Z",
        requirements_only=False,
    )

    assert success is True, "public-index lock + requirements generation should succeed"
    assert cmds, "expected uv lock/export and pylock-to-requirements invocations"
    assert cmds[0][:2] == [str(pg.UV), "lock"], f"first command should be uv lock: {cmds[0]}"
    assert cmds[1][:2] == [str(pg.UV), "export"], f"second command should be uv export: {cmds[1]}"
    assert "--python=3.12" in cmds[0], f"uv lock must pin image Python, not repo CI Python: {cmds[0]}"
    assert "--python=3.12" in cmds[1], f"uv export must pin image Python, not repo CI Python: {cmds[1]}"
    assert "--quiet" in cmds[0], f"uv lock should be quiet like rh-index pip compile: {cmds[0]}"
    assert "--quiet" in cmds[1], f"uv export should be quiet like rh-index pip compile: {cmds[1]}"
    assert cmds[-1] == [
        pg.sys.executable,
        str(pg.PYLOCK_TO_REQUIREMENTS),
        "--sdist-hashes",
        "prefer",
        str(project_dir / "pylock.toml"),
        str(project_dir / "requirements.cpu.txt"),
    ], f"last command should convert root pylock.toml: {cmds[-1]}"


def test_process_directory_public_index_sanitizes_export_header(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = _public_index_project(tmp_path)

    def fake_run(cmd, **kwargs):
        if cmd[:2] == [str(pg.UV), "export"]:
            (project_dir / "pylock.toml").write_text(
                "# This file was autogenerated by uv via the following command:\n"
                "#    uv export --python=3.12 --format pylock.toml --output-file pylock.toml"
                " --no-annotate --emit-index-url --exclude-newer=2026-01-01T00:00:00Z\n"
                'lock-version = "1.0"\n',
                encoding="utf-8",
            )
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    _path, success, _log = pg.process_directory(
        project_dir,
        pg.IndexMode.public_index,
        False,
        False,
        "2026-01-01T00:00:00Z",
        requirements_only=False,
    )

    assert success is True
    header = (project_dir / "pylock.toml").read_text(encoding="utf-8").splitlines()[1]
    assert header.startswith("#    uv export --python=3.12"), f"sanitized header expected: {header}"
    assert "--exclude-newer" not in header, f"cutoff must not be committed in header: {header}"


def test_image_project_dir_for_repo_file_jupyter(repo_root: Path) -> None:
    project = repo_root / "jupyter" / "minimal" / "ubi9-python-3.12"
    assert pg.image_project_dir_for_repo_file("jupyter/minimal/ubi9-python-3.12/pyproject.toml") == project, (
        "jupyter pyproject.toml should map to image project dir"
    )


def test_image_project_dir_for_repo_file_codeserver(repo_root: Path) -> None:
    project = repo_root / "codeserver" / "ubi9-python-3.12"
    assert pg.image_project_dir_for_repo_file("codeserver/ubi9-python-3.12/uv.lock.d/pylock.cpu.toml") == project, (
        "codeserver pylock path should map to image project dir"
    )


def test_is_lock_chain_file(subtests: pytest.Subtests) -> None:
    cases = [
        (Path("pyproject.toml"), True),
        (Path("uv.lock.d/pylock.cpu.toml"), True),
        (Path("requirements.cpu.txt"), True),
        (Path("README.md"), False),
    ]
    for path, expected in cases:
        with subtests.test(path=str(path)):
            assert pg._is_lock_chain_file(path) is expected, f"{path} lock-chain={expected}"


def test_resolve_pr_scoped_touched_requirements(
    repo_root: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        pg,
        "_list_changed_files",
        lambda _base, _to="HEAD": ["jupyter/minimal/ubi9-python-3.12/requirements.cuda.txt"],
    )
    expected = repo_root / "jupyter" / "minimal" / "ubi9-python-3.12"
    assert pg.resolve_pr_scoped_target_dirs("base", pg.LogBuffer()) == [expected], (
        "requirements.txt change should scope to touched image dir"
    )


def test_resolve_pr_scoped_diffs_from_base_ref(
    repo_root: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    base_ref = "origin/main"
    head_ref = "rhaieng-6397-scoped-pr-lock-regen"
    changed_files_mock = Mock(
        return_value=["jupyter/minimal/ubi9-python-3.12/pyproject.toml"],
    )
    monkeypatch.setattr(pg, "_list_changed_files", changed_files_mock)
    expected = repo_root / "jupyter" / "minimal" / "ubi9-python-3.12"
    assert pg.resolve_pr_scoped_target_dirs(base_ref, pg.LogBuffer(), pr_to_ref=head_ref) == [expected], (
        "three-dot diff from base ref should scope to touched image dir"
    )
    changed_files_mock.assert_called_once_with(base_ref, head_ref)


def test_resolve_pr_scoped_skips_unrelated(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(pg, "_list_changed_files", lambda _base, _to="HEAD": ["README.md"])
    assert pg.resolve_pr_scoped_target_dirs("base", pg.LogBuffer()) == [], (
        "unrelated file changes should not trigger lock regen"
    )


def test_resolve_pr_scoped_touched_pyproject(
    repo_root: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        pg,
        "_list_changed_files",
        lambda _base, _to="HEAD": ["jupyter/minimal/ubi9-python-3.12/pyproject.toml"],
    )
    expected = repo_root / "jupyter" / "minimal" / "ubi9-python-3.12"
    assert pg.resolve_pr_scoped_target_dirs("base", pg.LogBuffer()) == [expected], (
        "pyproject.toml change should scope to touched image dir"
    )


def test_resolve_pr_scoped_touched_codeserver(
    repo_root: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        pg,
        "_list_changed_files",
        lambda _base, _to="HEAD": ["codeserver/ubi9-python-3.12/pyproject.toml"],
    )
    expected = repo_root / "codeserver" / "ubi9-python-3.12"
    assert pg.resolve_pr_scoped_target_dirs("base", pg.LogBuffer()) == [expected], (
        "codeserver pyproject.toml change should scope to touched image dir"
    )


def test_global_lock_inputs_include_constraints_and_overrides() -> None:
    assert Path("dependencies/constraints.txt") in pg.GLOBAL_LOCK_INPUTS
    assert Path("dependencies/overrides.txt") in pg.GLOBAL_LOCK_INPUTS


def test_run_lock_always_passes_constraints_and_overrides(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "jupyter" / "minimal" / "ubi9-python-3.12"
    project_dir.mkdir(parents=True)
    (project_dir / "pyproject.toml").write_text('[project]\nname = "test"\n', encoding="utf-8")
    log = pg.LogBuffer()
    captured_cmd: list[str] = []

    def fake_run(cmd, **kwargs):
        captured_cmd[:] = cmd
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    success = pg.run_lock(
        project_dir,
        "cpu",
        ["--default-index=https://example.invalid/simple/?format=json"],
        pg.IndexMode.rh_index,
        "3.12",
        False,
        False,
        "2026-05-18T00:00:00Z",
        log,
    )

    assert success is True
    expected_constraints = os.path.relpath(pg.CONSTRAINTS_FILE, project_dir)
    expected_overrides = os.path.relpath(pg.OVERRIDES_FILE, project_dir)
    constraints_idx = captured_cmd.index("--constraints")
    overrides_idx = captured_cmd.index("--override")
    assert captured_cmd[constraints_idx + 1] == expected_constraints, (
        f"expected constraints path {expected_constraints!r}, got {captured_cmd[constraints_idx + 1]!r}"
    )
    assert captured_cmd[overrides_idx + 1] == expected_overrides, (
        f"expected overrides path {expected_overrides!r}, got {captured_cmd[overrides_idx + 1]!r}"
    )


def test_run_lock_appends_extra_alignment_constraints(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "jupyter" / "baseline" / "ubi9-python-3.12"
    project_dir.mkdir(parents=True)
    original_pyproject = '[project]\nname = "test"\n\n[tool.uv.sources]\n'
    (project_dir / "pyproject.toml").write_text(original_pyproject, encoding="utf-8")
    extra_constraints = project_dir / ".aipcc-alignment.constraints.txt"
    extra_constraints.write_text("uv==0.1.0\n", encoding="utf-8")
    log = pg.LogBuffer()
    captured_cmds: list[list[str]] = []
    patched_during_lock: list[str] = []

    def fake_run(cmd, **kwargs):
        captured_cmds.append(list(cmd))
        if cmd[:2] == [str(pg.UV), "lock"]:
            patched_during_lock.append((project_dir / "pyproject.toml").read_text(encoding="utf-8"))
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    success = pg.run_lock(
        project_dir,
        "cpu",
        ["--default-index=https://example.invalid/simple/?format=json"],
        pg.IndexMode.public_index,
        "3.12",
        False,
        False,
        "2026-05-18T00:00:00Z",
        log,
        extra_constraints,
    )

    assert success is True
    assert captured_cmds, "expected uv lock/export invocations"
    assert captured_cmds[0][:2] == [str(pg.UV), "lock"]
    assert "--python=3.12" in captured_cmds[0], f"uv lock must pin image Python, not repo CI Python: {captured_cmds[0]}"
    assert "--python=3.12" in captured_cmds[1], (
        f"uv export must pin image Python, not repo CI Python: {captured_cmds[1]}"
    )
    assert "--quiet" in captured_cmds[0]
    assert "--quiet" in captured_cmds[1]
    assert patched_during_lock, "expected patched pyproject during uv lock"
    patched_document = tomllib.loads(patched_during_lock[0])
    patched_constraints = patched_document["tool"]["uv"]["constraint-dependencies"]
    assert "uv==0.1.0" in patched_constraints
    assert "constraint-dependencies" not in patched_document
    assert (project_dir / "pyproject.toml").read_text(encoding="utf-8") == original_pyproject, (
        "pyproject.toml must be restored after public-index lock generation"
    )


def test_inject_tool_uv_constraint_dependencies_creates_tool_uv_table_before_sources() -> None:
    original = '[project]\nname = "test"\n\n[tool.uv.sources]\nfoo = "bar"\n'
    patched = pg._inject_tool_uv_constraint_dependencies(original, ["uv==0.1.0"])
    document = tomllib.loads(patched)
    assert document["tool"]["uv"]["constraint-dependencies"] == ["uv==0.1.0"]
    assert "[tool.uv]" in patched
    assert patched.index("[tool.uv]") < patched.index("[tool.uv.sources]")


def test_inject_tool_uv_constraint_dependencies_merges_into_existing_tool_uv_table() -> None:
    original = (
        """
[tool.uv]
exclude-dependencies = ["py-spy"]
constraint-dependencies = [
    "wheel==0.48.0",
]

[tool.uv.sources]
""".strip()
        + "\n"
    )
    patched = pg._inject_tool_uv_constraint_dependencies(original, ["uv==0.1.0", "wheel==0.48.0"])
    document = tomllib.loads(patched)
    assert document["tool"]["uv"]["constraint-dependencies"] == ["wheel==0.48.0", "uv==0.1.0"]
    assert document["tool"]["uv"]["exclude-dependencies"] == ["py-spy"]


def test_inject_tool_uv_constraint_dependencies_ignores_comment_mentions() -> None:
    original = (
        """
[project]
name = "test"

# constraint-dependencies is documented elsewhere

[tool.uv.sources]
""".strip()
        + "\n"
    )
    patched = pg._inject_tool_uv_constraint_dependencies(original, ["uv==0.1.0"])
    document = tomllib.loads(patched)
    assert document["tool"]["uv"]["constraint-dependencies"] == ["uv==0.1.0"]


def test_generate_baseline_alignment_constraints_uses_pair_and_alias(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = tmp_path
    baseline_rel = Path("jupyter/baseline/ubi9-python-3.12")
    source_rel = Path("jupyter/datascience/ubi9-python-3.12")
    baseline_dir = root / baseline_rel
    source_dir = root / source_rel
    baseline_dir.mkdir(parents=True)
    source_dir.mkdir(parents=True)
    (baseline_dir / "pyproject.toml").write_text(
        """
[project]
name = "baseline-test"
version = "0.1.0"
dependencies = [
  "pandas",
  "pandoc",
  "ripgrep==14.1.0",
  "uv",
]
""".strip()
        + "\n",
        encoding="utf-8",
    )
    (source_dir / "requirements.cpu.txt").write_text(
        """
--index-url https://example.invalid/simple
pandas==2.3.3 ; sys_platform == 'linux'
pandoc-rhai==3.8.0 ; sys_platform == 'linux'
ripgrep==15.1.0 ; sys_platform == 'linux'
""".strip()
        + "\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(pg, "ROOT_DIR", root)
    monkeypatch.setattr(pg, "BASELINE_AIPCC_ALIGNMENT_PAIRS", {baseline_rel: source_rel})
    monkeypatch.setattr(pg, "BASELINE_AIPCC_ALIGNMENT_SOURCE_ALIASES", {"pandoc": "pandoc-rhai"})
    monkeypatch.setattr(pg, "BASELINE_AIPCC_ALIGNMENT_SKIP_PACKAGES", frozenset({"ripgrep"}))

    generated = pg.generate_baseline_alignment_constraints(baseline_dir, pg.LogBuffer())

    assert generated is not None
    assert generated == baseline_dir / pg.AIPCC_ALIGNMENT_CONSTRAINTS_FILENAME
    content = generated.read_text(encoding="utf-8")
    assert "pandas==2.3.3" in content
    assert "pandoc==3.8.0" in content
    assert "uv==" not in content
    assert "ripgrep==" not in content
    generated.unlink(missing_ok=True)


def test_generate_baseline_alignment_constraints_skips_when_source_missing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = tmp_path
    baseline_rel = Path("runtimes/baseline/ubi9-python-3.12")
    source_rel = Path("runtimes/datascience/ubi9-python-3.12")
    baseline_dir = root / baseline_rel
    baseline_dir.mkdir(parents=True)
    (baseline_dir / "pyproject.toml").write_text(
        """
[project]
name = "runtime-baseline-test"
version = "0.1.0"
dependencies = ["uv"]
""".strip()
        + "\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(pg, "ROOT_DIR", root)
    monkeypatch.setattr(pg, "BASELINE_AIPCC_ALIGNMENT_PAIRS", {baseline_rel: source_rel})

    generated = pg.generate_baseline_alignment_constraints(baseline_dir, pg.LogBuffer())

    assert generated is None
    assert not (baseline_dir / ".aipcc-alignment.constraints.txt").exists()


@pytest.mark.parametrize(
    "global_input",
    ["dependencies/constraints.txt", "dependencies/overrides.txt"],
)
def test_resolve_pr_scoped_global_input_expands_to_all(
    global_input: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        pg,
        "_list_changed_files",
        lambda _base, _to="HEAD": [global_input],
    )
    scoped = pg.resolve_pr_scoped_target_dirs("base", pg.LogBuffer())
    all_dirs = pg.discover_all_image_project_dirs()
    assert scoped == all_dirs, f"{global_input} change should expand to all image dirs"
    assert len(scoped) > 1, "expected multiple image project dirs for global-input fallback"
