"""Unit tests for pylocks_generator exclude-newer helpers."""

from __future__ import annotations

from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[3]
# _SCRIPTS = _REPO_ROOT / "scripts"
# if str(_SCRIPTS) not in sys.path:
#     sys.path.insert(0, str(_SCRIPTS))

import scripts.index_url_resolver as resolver  # noqa: E402
import scripts.pylocks_generator as pg  # noqa: E402


@pytest.fixture
def repo_root() -> Path:
    return _REPO_ROOT


def test_utc_now_iso_format() -> None:
    s = pg.utc_now_iso()
    assert len(s) == 20
    assert s.endswith("Z")
    assert "T" in s


def test_parse_exclude_newer_equals_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --exclude-newer=2025-06-01T12:30:45Z --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45Z"


def test_parse_exclude_newer_space_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --exclude-newer 2025-06-01T12:30:45Z --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45Z"


def test_parse_exclude_newer_offset_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile --exclude-newer=2025-06-01T12:30:45+00:00 x\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45+00:00"


def test_parse_exclude_newer_missing(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) is None


def test_parse_exclude_newer_missing_file(tmp_path: Path) -> None:
    assert pg.parse_exclude_newer_from_lockfile(tmp_path / "nope.toml") is None


def test_parse_exclude_newer_real_cpu_lock_header(repo_root: Path) -> None:
    sample = repo_root / "jupyter" / "datascience" / "ubi9-python-3.12" / "uv.lock.d" / "pylock.cpu.toml"
    if not sample.is_file():
        pytest.skip("sample lockfile not present")
    parsed = pg.parse_exclude_newer_from_lockfile(sample)
    assert parsed is not None


def test_resolve_exclude_newer_live_mode(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text("# no exclude\n", encoding="utf-8")
    assert pg.resolve_exclude_newer(p, ci_check=False, live_timestamp="2020-01-01T00:00:00Z") == (
        "2020-01-01T00:00:00Z"
    )


def test_resolve_exclude_newer_ci_parsed(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile --exclude-newer=2099-01-01T00:00:00Z\n",
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == ("2099-01-01T00:00:00Z")


def test_resolve_exclude_newer_ci_fallback(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "#    uv pip compile pyproject.toml --quiet\n",
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == ("2020-01-01T00:00:00Z")


class TestEnsureJsonFormatParam:
    def test_bare_url(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/") == ("https://example.com/simple/?format=json")

    def test_no_trailing_slash(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple") == ("https://example.com/simple?format=json")

    def test_already_has_format_json(self) -> None:
        url = "https://example.com/simple/?format=json"
        assert pg.ensure_json_format_param(url) == url

    def test_overwrites_non_json_format(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/?format=html") == (
            "https://example.com/simple/?format=json"
        )

    def test_other_query_params(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/?other=1") == (
            "https://example.com/simple/?other=1&format=json"
        )

    def test_real_aipcc_url(self) -> None:
        url = "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cpu-ubi9/simple/"
        result = pg.ensure_json_format_param(url)
        assert result == url + "?format=json"
        assert pg.ensure_json_format_param(result) == result


def test_get_index_flags_uses_konflux_conf(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "project"
    build_args = project_dir / "build-args"
    build_args.mkdir(parents=True)
    (build_args / "konflux.cpu.conf").write_text(
        "BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-ea.2-1778762488\nPYLOCK_FLAVOR=cpu\nPRODUCT=rhoai\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(
        resolver,
        "index_url_exists",
        lambda url: url == "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9/simple/",
    )

    flags = pg.get_index_flags(project_dir, "cpu", pg.LogBuffer())

    assert flags == [
        "--default-index=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9/simple/?format=json",
    ]


def test_get_index_flags_falls_back_to_test_index(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "project"
    build_args = project_dir / "build-args"
    build_args.mkdir(parents=True)
    (build_args / "konflux.cpu.conf").write_text(
        "BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-ea.2-1778762488\nPYLOCK_FLAVOR=cpu\nPRODUCT=rhoai\n",
        encoding="utf-8",
    )

    monkeypatch.setattr(
        resolver,
        "index_url_exists",
        lambda url: url.endswith("/cpu-ubi9-test/simple/"),
    )

    flags = pg.get_index_flags(project_dir, "cpu", pg.LogBuffer())

    assert flags == [
        "--default-index=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9-test/simple/?format=json",
    ]


def test_run_lock_logs_index_url(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()

    log = pg.LogBuffer()
    completed = pg.subprocess.CompletedProcess(args=["uv"], returncode=0, stdout="", stderr="")

    def fake_run(*args, **kwargs):
        return completed

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    success = pg.run_lock(
        project_dir,
        "cpu",
        ["--default-index=https://example.invalid/simple/?format=json"],
        pg.IndexMode.rh_index,
        "3.12",
        False,
        False,
        "2026-05-18T00:00:00Z",
        log,
    )

    assert success is True
    assert any("Lock INDEX_URL: https://example.invalid/simple/?format=json" in line for line in log._lines)


def test_generate_requirements_txt_falls_back_to_pylock_header_when_index_resolution_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    log = pg.LogBuffer()
    captured_cmd: list[str] = []

    def fake_run(cmd, **kwargs):
        captured_cmd[:] = cmd
        return pg.subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg, "resolve_rh_index_config", lambda *args, **kwargs: None)
    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    success = pg.generate_requirements_txt(project_dir, "cpu", log)

    assert success is True
    assert captured_cmd == [
        pg.sys.executable,
        str(pg.PYLOCK_TO_REQUIREMENTS),
        str(project_dir / "uv.lock.d" / "pylock.cpu.toml"),
        str(project_dir / "requirements.cpu.txt"),
    ]
