#####################################
# pyarrow builder stage for ppc64le #
#####################################

FROM cpu-base AS arrow-builder

USER root
WORKDIR /root

ENV PYARROW_VERSION=17.0.0

RUN /bin/bash <<'EOF'
set -Eeuxo pipefail

git clone -b apache-arrow-${PYARROW_VERSION} https://github.com/apache/arrow.git --recursive
cd arrow && rm -rf .git && mkdir dist
pip3 install --no-cache-dir -r python/requirements-build.txt

ARROW_HOME=$(pwd)/dist

export ARROW_HOME
LD_LIBRARY_PATH=$(pwd)/dist/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

export LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$ARROW_HOME:$CMAKE_PREFIX_PATH
export PARQUET_TEST_DATA="${PWD}/cpp/submodules/parquet-testing/data"
export ARROW_TEST_DATA="${PWD}/testing/data"

cmake -S cpp -B cpp/build \
    -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
    -DCMAKE_BUILD_TYPE=release \
    -DARROW_WITH_BZ2=ON \
    -DARROW_WITH_ZLIB=ON \
    -DARROW_WITH_ZSTD=ON \
    -DARROW_WITH_LZ4=ON \
    -DARROW_WITH_SNAPPY=ON \
    -DARROW_WITH_BROTLI=ON \
    -DARROW_DATASET=ON \
    -DARROW_FILESYSTEM=ON \
    -DARROW_COMPUTE=ON \
    -DARROW_JSON=ON \
    -DARROW_CSV=ON \
    -DARROW_PYTHON=ON \
    -DARROW_PARQUET=ON \
    -DARROW_BUILD_SHARED=ON \
    -DARROW_BUILD_TESTS=OFF

cd cpp/build
make -j20 install

export PYARROW_PARALLEL=20
export PYARROW_WITH_PARQUET=1
export PYARROW_WITH_DATASET=1
export PYARROW_BUNDLE_ARROW_CPP=1

pip3 install --no-cache-dir wheel

cd ../../python

python setup.py build_ext \
    --build-type=release \
    --bundle-arrow-cpp \
    bdist_wheel --dist-dir /arrowwheels
EOF
