# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest@sha256:6da75ee8c1e30cb72d6357c486f4166f8951ddca22fc6a1934b7c162f19cd42e
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-datascience-cpu-py312-ubi9
PRODUCT=odh
RELEASE=3.6
