BASE_IMAGE=registry.access.redhat.com/ubi9/python-312:latest
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-datascience-cpu-py312-ubi9
PRODUCT=odh
RELEASE=3.5
