# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu-el9.8:3.6.0-1789756226@sha256:a22dace102a38678e7253e3affb35bce61cfa8db1bad6c271f0fcde2adc1da7b
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-datascience-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
