# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/rocm-7.14-el9.8:3.6.0-ea.1-1787158791@sha256:7fb9957db641a072b8470a52c7c1b52dc43a5bbfddc510156dc875da4fdf9c0f
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-rocm-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
