# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:v7.14@sha256:63313cce5673c865bb53426ece8a8c5fb719c87986e13d5df3f7ed5d5506a3ed
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-rocm-py312-ubi9
PRODUCT=odh
RELEASE=3.6
