# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu-el9.8:3.6.0-ea.1-1787782268@sha256:43a9d35d49e2205a74812dabcb1e328181def17ecd31a4845cdca6ded3887040
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-trustyai-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
