# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.6.0-ea.1-1785341085@sha256:38f6927ab1e17a805023d88456e97f07dd66004321be74dd31c2e7a176bd555e
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-trustyai-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
