# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu-el9.8:3.6.0-ea.2-1789393564@sha256:0307171e295ca58fc3326277a6f2fce10b10022c3af8e33be51210c584ceab20
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-trustyai-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
