#!/bin/sh

# based on https://github.com/sclorg/container-common-scripts/blob/4f4f13847fd372c304503bc0bf8e11fae6ce9e06/shared-scripts/core/usr/bin/fix-permissions

# Allow this script to fail without failing a build
set +e

SYMLINK_OPT=${2:--L}

# Fix permissions on the given directory or file to allow group read/write of
# regular files and execute of directories.

[ $(id -u) -ne 0 ] && CHECK_OWNER=" -uid $(id -u)"

# If argument does not exist, script will still exit with 0,
# but at least we'll see something went wrong in the log
if ! [ -e "$1" ] ; then
  echo "ERROR: File or directory $1 does not exist." >&2
  # We still want to end successfully
  exit 0
fi

# added line
find $SYMLINK_OPT "$1" ${CHECK_OWNER} \! -uid ${CNB_USER_ID:?} -exec chown ${CNB_USER_ID:?} {} +
# modified line
find $SYMLINK_OPT "$1" ${CHECK_OWNER} \! -gid ${CNB_GROUP_ID:?} -exec chgrp ${CNB_GROUP_ID:?} {} +
find $SYMLINK_OPT "$1" ${CHECK_OWNER} \! -perm -g+rw -exec chmod g+rw {} +
find $SYMLINK_OPT "$1" ${CHECK_OWNER} -perm /u+x -a \! -perm /g+x -exec chmod g+x {} +
find $SYMLINK_OPT "$1" ${CHECK_OWNER} -type d \! -perm /g+x -exec chmod g+x {} +

# Always end successfully
exit 0
