---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    opendatahub.io/runtime-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "Runtime | TensorFlow | CUDA | Python 3.12 | 2025.2"
    opendatahub.io/runtime-image-desc: "TensorFlow runtime image for Elyra, enabling pipeline execution from Workbenches with TensorFlow libraries and dependencies, supporting different runtimes for various pipeline nodes."
  name: runtime-tensorflow-2025-2
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "Runtime | TensorFlow | CUDA | Python 3.12 | 2025.2",
              "metadata": {
                "tags": [
                  "tensorflow-2025.2"
                ],
                "display_name": "Runtime | TensorFlow | CUDA | Python 3.12 | 2025.2",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: registry.redhat.io/rhoai/odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
      from:
        kind: DockerImage
        name: odh-pipeline-runtime-tensorflow-cuda-py312-ubi9-2025-2_PLACEHOLDER
      name: "tensorflow-2025-2"
      referencePolicy:
        type: Source
