# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/rocm-7.14-el9.8:3.6.0-ea.2-1789502329@sha256:86c6fa55f4686afe49b155bdc036592df3ae7908cfb095a25ae164cf22edaec6
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-rocm-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
