# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/rocm-7.14-el9.6:3.6.0-ea.1-1784899202@sha256:c89c2c0161c6bf9ffd07d80e948f2db178d99340b3a9e0ce68b1316e0a7abe11
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-rocm-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
