INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/rocm7.1-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/rocm-7.1-el9.6:3.5.0-ea.1-1778521387
PYLOCK_FLAVOR=rocm
PRODUCT=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-rocm-py312-rhel9
