BASE_IMAGE=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:on-pr-bd5a546c3c512c1b21b546cdb191c32781fa838c
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-rocm-py312-ubi9
PRODUCT=odh
