---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/codeserver/che-code-ubi9-python-3.12"
    opendatahub.io/notebook-image-name: "VS Code | CPU | Python 3.12"
    opendatahub.io/notebook-image-desc: "VS Code workbench powered by che-code, providing a browser-based development environment with Jupyter notebook support."
    opendatahub.io/notebook-image-order: "23"
  name: che-code-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "VS Code", "version": "1.116"},
            {"name": "Python", "version": "v3.12"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "ipykernel", "version": "7.3"},
            {"name": "notebook", "version": "7.4"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-workbench-che-code-cpu-py312-ubi9
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-workbench-che-code-cpu-py312-ubi9-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-che-code-cpu-py312-ubi9-n_PLACEHOLDER
      name: "3.5"
      referencePolicy:
        type: Source
