# Spyre accelerator build configuration
# BASE_IMAGE: the Spyre base image from quay.io/aipcc/base-images

BASE_IMAGE=quay.io/aipcc/base-images/spyre-el9.8:3.6@sha256:7570f65bdd95bfc2359de3b5dbfb1600ccf951ab39e3b1e24ef9a8fc218990c2
PYLOCK_FLAVOR=spyre
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-spyre-py312
PRODUCT=rhoai
RELEASE=3.6
