






















































































COPY ${RSTUDIO_SOURCE_CODE}/rsession.conf /etc/rstudio/rsession.conf

# Install R packages
ENV MAKEFLAGS="-j2"
ENV MAKEFLAGS="-j2"
ENV MAKEFLAGS="-j2"
ENV MAKEFLAGS="-j2"
# https://cran.r-project.org/web/packages
COPY ${RSTUDIO_SOURCE_CODE}/install_packages.R ./
RUN R -f ./install_packages.R && \