#!/usr/bin/env python3
"""Convert a pylock.toml (PEP 751) to a pip-compatible requirements.txt.

This helper is called by create-requirements-lockfile.sh (Step 2) to transform
a uv-generated pylock.toml lock file into a requirements.txt that pip, uv, and
cachi2/Hermeto can consume.

Why not just use pylock.toml directly?
  - pip and cachi2 don't support pylock.toml (PEP 751) yet.
  - requirements.txt with --hash lines is the common format understood by
    pip install --require-hashes, uv pip install --verify-hashes, and cachi2
    pip prefetch.

Usage:
    python3 pylock-to-requirements.py [--sdist-hashes MODE] \\
        <pylock.toml> <requirements.txt> [index-url]

Arguments:
    pylock.toml       Input lock file (PEP 751 format, generated by uv pip compile)
    requirements.txt  Output file path
    index-url         (optional) PyPI index URL to emit as --index-url header line.
                      If omitted or empty, the URL is taken from the uv compile comment
                      in the pylock (--default-index=...) so the requirements file matches
                      the index the lock was resolved against.

    --sdist-hashes    el9-fallback (default): omit sdist hashes when an EL9-compatible
                      wheel exists (RH-index / Hermeto wheel prefetch).
                      prefer: always include sdist hashes so ppc64le/s390x (no
                      manylinux wheels) and Hermeto source-only prefetch can match
                      artifacts (public-index baseline images).

Output format:
    Each package entry becomes a line like:
        name==version ; marker \\
            --hash=sha256:abc123 \\
            --hash=sha256:def456

    Pure-Python packages (py3-none-any.whl) have a single hash.
    Native/binary packages have one hash per architecture wheel.
    Sdist hashes follow --sdist-hashes (see above).

    Packages locked as a direct URL (uv ``archive``) become ``name @ URL`` so
    pip/Hermeto do not look them up on the index (e.g. tensorflow-rocm from AMD).

    If index-url is provided, it is emitted as the first line:
        --index-url https://...
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

from packaging.utils import InvalidWheelFilename, parse_wheel_filename

# uv pip compile records its index in the first-line comment, e.g.
#   --default-index=https://pypi.org/simple
_DEFAULT_INDEX_RE = re.compile(r"--default-index=(https?://\S+)")

# UBI9/EL9 ships glibc 2.34. manylinux_2_35+ wheels cannot be installed there.
# Target EL9 off-host (this converter does not run on UBI9), so sys_tags() is wrong.
_MAX_EL9_GLIBC = (2, 34)

SDIST_HASHES_EL9_FALLBACK = "el9-fallback"
SDIST_HASHES_PREFER = "prefer"


def strip_format_json_param(index_url: str) -> str:
    parsed = urlparse(index_url)
    query_items = [
        (key, value)
        for key, value in parse_qsl(parsed.query, keep_blank_values=True)
        if not (key == "format" and value == "json")
    ]
    normalized_query = urlencode(query_items, doseq=True)
    return urlunparse(parsed._replace(query=normalized_query))


def wheel_is_el9_compatible(url_or_name: str) -> bool:
    """Return True if this wheel can install on UBI9/EL9 (glibc 2.34).

    Uses ``parse_wheel_filename`` Tag.platform values only — never the
    distribution name (e.g. a package named manylinux2010_helper).
    """
    try:
        *_, tags = parse_wheel_filename(url_or_name.rsplit("/", 1)[-1])
    except InvalidWheelFilename:
        return False

    for tag in tags:
        platform = tag.platform
        if platform == "any" or platform.startswith(("manylinux1_", "manylinux2010_", "manylinux2014_")):
            return True
        if platform.startswith("manylinux_"):
            # PEP 600: manylinux_{major}_{minor}_{arch}
            parts = platform.split("_")
            if (
                len(parts) >= 4
                and parts[1].isdigit()
                and parts[2].isdigit()
                and (int(parts[1]), int(parts[2])) <= _MAX_EL9_GLIBC
            ):
                return True
    return False


def collect_index_hashes(pkg: dict, *, sdist_hashes: str = SDIST_HASHES_EL9_FALLBACK) -> list[str]:
    """Return wheel ``--hash=`` lines; sdist hashes depend on ``sdist_hashes``.

    ``el9-fallback`` (default): add sdist hashes only when no EL9 wheel exists.
    ``prefer``: always include sdist hashes when present (ppc64le/s390x, Hermeto).
    """
    hashes: list[str] = []
    has_el9_wheel = False
    for whl in pkg.get("wheels", []):
        for algo, digest in whl.get("hashes", {}).items():
            hashes.append(f"--hash={algo}:{digest}")
        if wheel_is_el9_compatible(whl.get("url", "")):
            has_el9_wheel = True

    include_sdist = sdist_hashes == SDIST_HASHES_PREFER or not has_el9_wheel
    if include_sdist:
        sdist = pkg.get("sdist")
        if isinstance(sdist, dict):
            for algo, digest in sdist.get("hashes", {}).items():
                hashes.append(f"--hash={algo}:{digest}")
    return hashes


def extract_default_index_from_pylock(pylock_path: Path) -> str:
    """Return --default-index URL from the uv autogeneration comment, or ""."""
    try:
        head = pylock_path.read_text(encoding="utf-8", errors="replace")[:8192]
    except OSError:
        return ""
    m = _DEFAULT_INDEX_RE.search(head)
    return strip_format_json_param(m.group(1).rstrip("'\"")) if m else ""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("pylock_toml", type=Path, help="Input PEP 751 pylock.toml")
    parser.add_argument("requirements_txt", type=Path, help="Output requirements.txt path")
    parser.add_argument(
        "index_url",
        nargs="?",
        default="",
        help="Optional --index-url header. Empty uses the pylock --default-index comment.",
    )
    parser.add_argument(
        "--sdist-hashes",
        choices=(SDIST_HASHES_EL9_FALLBACK, SDIST_HASHES_PREFER),
        default=SDIST_HASHES_EL9_FALLBACK,
        help="When to emit sdist hashes (default: el9-fallback).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    pylock_path: Path = args.pylock_toml
    output_path: Path = args.requirements_txt
    index_url = args.index_url.strip() or extract_default_index_from_pylock(pylock_path)

    # Parse the pylock.toml (PEP 751 format, requires Python 3.11+ for tomllib)
    with open(pylock_path, "rb") as f:
        data = tomllib.load(f)

    lines = []

    # Emit --index-url as the first line so pip/uv know where to find packages
    if index_url:
        lines.append(f"--index-url {index_url}")

    # Process each [[packages]] entry from the lock file
    for pkg in data.get("packages", []):
        name = pkg["name"]
        version = pkg["version"]
        marker = pkg.get("marker", "")  # e.g. "sys_platform == 'linux'"

        archive = pkg.get("archive")
        if isinstance(archive, dict) and (archive_url := (archive.get("url") or "").strip()):
            # Direct URL (not on PyPI): PEP 508 "name @ URL" so prefetchers fetch this file.
            hashes = [f"--hash={algo}:{digest}" for algo, digest in archive.get("hashes", {}).items()]
            entry = f"{name} @ {archive_url}"
            if marker:
                entry += f" ; {marker}"
            if hashes:
                entry += " \\\n" + " \\\n".join(f"    {h}" for h in hashes)
            lines.append(entry)
            continue

        hashes = collect_index_hashes(pkg, sdist_hashes=args.sdist_hashes)

        entry = f"{name}=={version}"
        if marker:
            entry += f" ; {marker}"
        if hashes:
            entry += " \\\n" + " \\\n".join(f"    {h}" for h in hashes)

        lines.append(entry)

    # Write the output file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")

    pkg_count = len(lines) - (1 if index_url else 0)
    print(f"  Generated {output_path} ({pkg_count} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
