#!/usr/bin/env python3
"""Convert a pylock.toml (PEP 751) to a pip-compatible requirements.txt.

This helper is called by create-requirements-lockfile.sh (Step 2) to transform
a uv-generated pylock.toml lock file into a requirements.txt that pip, uv, and
cachi2 can consume.

Why not just use pylock.toml directly?
  - pip and cachi2 don't support pylock.toml (PEP 751) yet.
  - requirements.txt with --hash lines is the common format understood by
    pip install --require-hashes, uv pip install --verify-hashes, and cachi2
    pip prefetch.

Usage:
    python3 pylock-to-requirements.py <pylock.toml> <requirements.txt> [index-url]

Arguments:
    pylock.toml       Input lock file (PEP 751 format, generated by uv pip compile)
    requirements.txt  Output file path
    index-url         (optional) PyPI index URL to emit as --index-url header line.
                      If omitted or empty, the URL is taken from the uv compile comment
                      in the pylock (--default-index=...) so the requirements file matches
                      the index the lock was resolved against.

Output format:
    Each package entry becomes a line like:
        name==version ; marker \\
            --hash=sha256:abc123 \\
            --hash=sha256:def456

    Pure-Python packages (py3-none-any.whl) have a single hash.
    Native/binary packages have one hash per architecture wheel.

    Packages locked as a direct URL (uv ``archive``) become ``name @ URL`` so
    pip/Hermeto do not look them up on the index (e.g. tensorflow-rocm from AMD).

    Wheels whose URLs are not served by the declared --index-url (e.g. RH pulp
    wheels while using PyPI as index) are emitted as ``name @ URL`` lines so
    hermeto does not require --extra-index-url.

    If index-url is provided, it is emitted as the first line:
        --index-url https://...
"""
from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

# uv pip compile records its index in the first-line comment, e.g.
#   --default-index=https://pypi.org/simple
_DEFAULT_INDEX_RE = re.compile(r"--default-index=(https?://\S+)")

_WHEEL_ARCH_RE = re.compile(
    r"linux_(?P<arch>x86_64|aarch64|ppc64le|s390x)(?:\.|/|$)",
    re.IGNORECASE,
)
# RHOAI wheels use {name}-{pypi-version}-{rh-rev}-cp… (e.g. matplotlib-3.11.0-4-cp312-…).
_RH_BUILD_REV_RE = re.compile(r"-(\d+)-(?:cp\d|abi3|py3)", re.IGNORECASE)


def strip_format_json_param(index_url: str) -> str:
    parsed = urlparse(index_url)
    query_items = [
        (key, value)
        for key, value in parse_qsl(parsed.query, keep_blank_values=True)
        if not (key == "format" and value == "json")
    ]
    normalized_query = urlencode(query_items, doseq=True)
    return urlunparse(parsed._replace(query=normalized_query))


def extract_default_index_from_pylock(pylock_path: Path) -> str:
    """Return --default-index URL from the uv autogeneration comment, or ""."""
    try:
        head = pylock_path.read_text(encoding="utf-8", errors="replace")[:8192]
    except OSError:
        return ""
    m = _DEFAULT_INDEX_RE.search(head)
    return strip_format_json_param(m.group(1).rstrip("'\"")) if m else ""


def index_url_serves_wheel(index_url: str, wheel_url: str) -> bool:
    if not index_url:
        return True
    index_host = urlparse(index_url).netloc
    wheel_host = urlparse(wheel_url).netloc
    if index_host == wheel_host:
        return True
    # PyPI simple index; wheels are served from files.pythonhosted.org.
    if "pypi.org" in index_host and wheel_host == "files.pythonhosted.org":
        return True
    # RH simple index; wheels are served from pulp-content host.
    if "packages.redhat.com" in index_host and "packages.redhat.com" in wheel_host:
        return True
    return False


def rh_build_revision(wheel_url: str) -> int:
    """Return RHOAI RPM-style build revision from wheel URL, or 0 if unknown."""
    filename = wheel_url.rsplit("/", 1)[-1]
    match = _RH_BUILD_REV_RE.search(filename)
    return int(match.group(1)) if match else 0


def wheel_arch_key(wheel_url: str) -> str:
    match = _WHEEL_ARCH_RE.search(wheel_url)
    if match is not None:
        return match.group("arch").lower()
    if wheel_url.endswith("py3-none-any.whl") or wheel_url.endswith("py2.py3-none-any.whl"):
        return "any"
    return "unknown"


def dedupe_off_index_wheels(wheels: list[dict]) -> list[dict]:
    """Keep one off-index wheel per architecture (highest RHOAI build revision).

    uv pip install --strict rejects multiple ``name @ URL`` lines for the same
    package on the same platform.  The RH index may publish several build
    revisions (-2, -3, …) for the same PyPI version; keep the newest only.
    """
    best: dict[str, tuple[int, dict]] = {}
    for whl in wheels:
        url = (whl.get("url") or "").strip()
        if not url:
            continue
        key = wheel_arch_key(url)
        rev = rh_build_revision(url)
        if key not in best or rev > best[key][0]:
            best[key] = (rev, whl)
    return [whl for _, whl in sorted(best.values(), key=lambda item: item[0])]


def arch_marker_from_wheel_url(wheel_url: str, base_marker: str) -> str:
    match = _WHEEL_ARCH_RE.search(wheel_url)
    if match is None:
        return base_marker
    arch = match.group("arch").lower()
    arch_clause = f"platform_machine == '{arch}'"
    if not base_marker:
        return arch_clause
    return f"({base_marker}) and {arch_clause}"


def le_only_marker(base_marker: str) -> str:
    """Restrict a universal marker to little-endian arches when BE uses direct URLs."""
    le_parts = [
        f"({base_marker}) and platform_machine == '{arch}'"
        for arch in ("x86_64", "aarch64")
    ]
    return " or ".join(le_parts)


def emit_direct_url_entry(name: str, url: str, marker: str, hashes: dict[str, str]) -> str:
    hash_lines = [f"--hash={algo}:{digest}" for algo, digest in hashes.items()]
    entry = f"{name} @ {url}"
    if marker:
        entry += f" ; {marker}"
    if hash_lines:
        entry += " \\\n" + " \\\n".join(f"    {h}" for h in hash_lines)
    return entry


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <pylock.toml> <requirements.txt> [index-url]",
              file=sys.stderr)
        sys.exit(1)

    pylock_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    if len(sys.argv) > 3 and sys.argv[3].strip():
        index_url = strip_format_json_param(sys.argv[3].strip())
    else:
        index_url = extract_default_index_from_pylock(pylock_path)

    # Parse the pylock.toml (PEP 751 format, requires Python 3.11+ for tomllib)
    with open(pylock_path, "rb") as f:
        data = tomllib.load(f)

    lines = []

    # Emit --index-url as the first line so pip/uv know where to find packages
    if index_url:
        lines.append(f"--index-url {index_url}")

    # Process each [[packages]] entry from the lock file
    for pkg in data.get("packages", []):
        name = pkg["name"]
        version = pkg["version"]
        marker = pkg.get("marker", "")  # e.g. "sys_platform == 'linux'"

        archive = pkg.get("archive")
        if isinstance(archive, dict) and (archive_url := (archive.get("url") or "").strip()):
            lines.append(
                emit_direct_url_entry(name, archive_url, marker, archive.get("hashes", {}))
            )
            continue

        wheels = pkg.get("wheels", [])
        sdist = pkg.get("sdist") if isinstance(pkg.get("sdist"), dict) else None
        on_index_wheels = [
            whl
            for whl in wheels
            if (whl.get("url") or "").strip()
            and index_url_serves_wheel(index_url, whl["url"])
        ]
        off_index_wheels = [
            whl
            for whl in wheels
            if (whl.get("url") or "").strip()
            and not index_url_serves_wheel(index_url, whl["url"])
        ]

        # Hermeto supports only one --index-url. Emit direct URLs for wheels that
        # live on another host (e.g. RH pulp wheels when index-url is PyPI).
        if off_index_wheels:
            for whl in dedupe_off_index_wheels(off_index_wheels):
                wheel_url = whl["url"].strip()
                wheel_marker = arch_marker_from_wheel_url(wheel_url, marker)
                lines.append(
                    emit_direct_url_entry(name, wheel_url, wheel_marker, whl.get("hashes", {}))
                )

        if on_index_wheels or sdist is not None:
            hashes = []
            for whl in on_index_wheels:
                for algo, digest in whl.get("hashes", {}).items():
                    hashes.append(f"--hash={algo}:{digest}")
            if sdist is not None:
                for algo, digest in sdist.get("hashes", {}).items():
                    hashes.append(f"--hash={algo}:{digest}")

            entry_marker = le_only_marker(marker) if off_index_wheels else marker
            entry = f"{name}=={version}"
            if entry_marker:
                entry += f" ; {entry_marker}"
            if hashes:
                entry += " \\\n" + " \\\n".join(f"    {h}" for h in hashes)
            lines.append(entry)
        elif not off_index_wheels:
            # No wheels at all — emit version pin for completeness.
            entry = f"{name}=={version}"
            if marker:
                entry += f" ; {marker}"
            lines.append(entry)

    # Write the output file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")

    pkg_count = len(lines) - (1 if index_url else 0)
    print(f"  Generated {output_path} ({pkg_count} packages)")


if __name__ == "__main__":
    main()
