#!/usr/bin/env python3
"""Convert a pylock.toml (PEP 751) to a pip-compatible requirements.txt.

This helper is called by create-requirements-lockfile.sh (Step 2) to transform
a uv-generated pylock.toml lock file into a requirements.txt that pip, uv, and
cachi2 can consume.

Why not just use pylock.toml directly?
  - pip and cachi2 don't support pylock.toml (PEP 751) yet.
  - requirements.txt with --hash lines is the common format understood by
    pip install --require-hashes, uv pip install --verify-hashes, and cachi2
    pip prefetch.

Usage:
    python3 pylock-to-requirements.py <pylock.toml> <requirements.txt> [index-url]

Arguments:
    pylock.toml       Input lock file (PEP 751 format, generated by uv pip compile)
    requirements.txt  Output file path
    index-url         (optional) PyPI index URL to emit as --index-url header line

Output format:
    Each package entry becomes a line like:
        name==version ; marker \\
            --hash=sha256:abc123 \\
            --hash=sha256:def456

    Pure-Python packages (py3-none-any.whl) have a single hash.
    Native/binary packages have one hash per architecture wheel.

    If index-url is provided, it is emitted as the first line:
        --index-url https://...
"""
import sys
import tomllib
from pathlib import Path


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <pylock.toml> <requirements.txt> [index-url]",
              file=sys.stderr)
        sys.exit(1)

    pylock_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    index_url = sys.argv[3] if len(sys.argv) > 3 else ""

    # Parse the pylock.toml (PEP 751 format, requires Python 3.11+ for tomllib)
    with open(pylock_path, "rb") as f:
        data = tomllib.load(f)

    lines = []

    # Emit --index-url as the first line so pip/uv know where to find packages
    if index_url:
        lines.append(f"--index-url {index_url}")

    # Process each [[packages]] entry from the lock file
    for pkg in data.get("packages", []):
        name = pkg["name"]
        version = pkg["version"]
        marker = pkg.get("marker", "")  # e.g. "sys_platform == 'linux'"

        # Collect sha256 hashes from all wheel entries for this package.
        # Multi-arch packages (numpy, uv, cffi, etc.) have multiple wheels,
        # each with a different hash — all must be listed so pip accepts
        # whichever wheel matches the current platform.
        hashes = []
        for whl in pkg.get("wheels", []):
            for algo, digest in whl.get("hashes", {}).items():
                hashes.append(f"--hash={algo}:{digest}")

        # Build the requirements.txt entry with version pin, marker, and hashes
        entry = f"{name}=={version}"
        if marker:
            entry += f" ; {marker}"
        if hashes:
            # Join hashes with backslash-newline continuation for readability
            entry += " \\\n" + " \\\n".join(f"    {h}" for h in hashes)

        lines.append(entry)

    # Write the output file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")

    pkg_count = len(lines) - (1 if index_url else 0)
    print(f"  Generated {output_path} ({pkg_count} packages)")


if __name__ == "__main__":
    main()
