######################################
# openblas builder stage for ppc64le #
######################################

FROM cpu-base AS openblas-builder

USER root
WORKDIR /root

ENV OPENBLAS_VERSION=0.3.30

RUN /bin/bash <<'EOF'
set -Eeuxo pipefail
source /opt/rh/gcc-toolset-13/enable
wget --progress=dot:giga https://github.com/OpenMathLib/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/OpenBLAS-${OPENBLAS_VERSION}.zip
unzip OpenBLAS-${OPENBLAS_VERSION}.zip && cd OpenBLAS-${OPENBLAS_VERSION}
make -j$(nproc) TARGET=POWER9 BINARY=64 USE_OPENMP=1 USE_THREAD=1 NUM_THREADS=120 DYNAMIC_ARCH=1 INTERFACE64=0
EOF
