# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:v7.14@sha256:9f6c1903a0939394c74b8fd4fce2c71fa4bb48742a0f736c4d7911a537cfc42f
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-tensorflow-rocm-py312-ubi9
PRODUCT=odh
RELEASE=3.6
