BASE_IMAGE=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:on-pr-a0bd21c6cf0e3fd1dd7b504430d1f6c5d313f4a8
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-tensorflow-rocm-py312-ubi9
PRODUCT=odh
