# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v13.0@sha256:df060d71715600987c0641df9a9ee4bc525cf86aca58e786667ecef319b8f6ec
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.6
