# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v13.0@sha256:8ebd26f30e68f96ceb7d6e6c7419b0a87890f9bc675b1d50ed33a236bbce7e7e
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.6
