# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.8:3.6.0-ea.1-1787266050@sha256:f857d095595d878075e76c514b5cb5847b689bca7ee53d60fd9de1e1c59e7d1e
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
