# Base Image   : RHEL 9.6 with Python 3.12
# CUDA Version : 12.9
# Architectures: linux/arm64, linux/x86_64
# Source       : https://quay.io/repository/aipcc/base-images/cuda
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.3.0-1768412345
INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4-EA1/cuda12.9-ubi9/simple/
# TODO(RHAIENG-3071): Add CPU index as fallback for packages not available in CUDA/ROCm indexes
CPU_INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4-EA1/cpu-ubi9/simple/
PYLOCK_FLAVOR=cuda
