# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cpu-py312-c9s@sha256:51696c5f359338bfff3706ea84fd87f354fc4363cff1ba6253a25e4783d2b3c6
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-minimal-cpu-py312-ubi9
PRODUCT=odh
RELEASE=3.5
