# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s@sha256:3d17071c62fb5f19e5920a08a30fc1bf02ddbece167e82e0119bb39190f19cbe
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-minimal-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.5
