# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.8:3.6.0-1791476877@sha256:47f60de824ea125e16ff3135a78e6f6a3380a9c06648d9b77c8f8cb90335dcac
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-minimal-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
