# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.6.0-ea.1-1785445403@sha256:30b181a17519ac72d8ebd9f93812dce86d3bf1be43519013b21ee6aa28877a75
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-minimal-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
