INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4-EA2/rocm6.4-ubi9/simple/
CPU_INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4-EA2/cpu-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/rocm-6.4-el9.6:3.4.0-ea.2-1772829805
PYLOCK_FLAVOR=rocm
