# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.8:3.6.0-ea.1-1787612272@sha256:9d2ef10dfc736169c01ab4e547d5e532b95906b415aaa7b6fd887aa4088a2609
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-minimal-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
