BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.6:3.5.0-ea.2-1779922316
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-minimal-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
