# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:v7.14@sha256:77e4b6556341598c001c7f485a28da74074ef23acc65f8256168cffe796c0707
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-minimal-rocm-py312-ubi9
PRODUCT=odh
RELEASE=3.6
