# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v12.9@sha256:725daf4e1a00c9c1ef2c9b49f2d7f2858a65ae80d9a854916a0e6b9e9443bc87
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.6
