# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v12.9@sha256:a4c1bd88de642119a38c44a9e85c63fdf78e5ee39ca27850ac7b69bc61851e29
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.6
