# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.6.0-ea.1-1785513455@sha256:e765a7952a6b0b5c7aceb432d34a1f4cda857506a5c522bc39744c3f5097374e
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
