# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.8:3.6.0-1791477715@sha256:486700ad47d99267b39f19654ea50cb0ab79afc73d560a555df7cfadb10526ed
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
