# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.5.0-1784224754@sha256:079ae5aaf9f9d9f98b61aaf59e27cf692a1f061b8d7f069cd4e5e480743e18b7
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
