# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v13.0@sha256:e42e80df19b0aa042d572a47ee9409310bfe113f00936755a3a14c3fe2b8bfae
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.5
