# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.6:3.6.0-ea.1-1784899049@sha256:3781b9b413717c17f70063bd12dd4e007ca4d2934da9d1b821a8c90cd2d253ee
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
