# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.8:3.6.0-ea.1-1787158775@sha256:c816ade0ef292dc49867c5d96eb91b5bd5cabe501e28539a682970382fd84b19
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
