# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/rocm-7.14-el9.8:3.6.0-ea.1-1787265973@sha256:af5e8677868b23e8d620903620a1eedfc3cb5b067952c5c428945c7d2a1653f9
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-rocm-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
