# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/rocm-7.14-el9.6:3.6.0-ea.1-1785340408@sha256:1ef9456a1df8c1d2ee2dd507bded59560fc2f7c38b6591bb2a0209012e270b3f
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-rocm-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
