# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:v7.14@sha256:b0a89ae435184213d1b01e9c933fddca3da71ac49c577f89d23c7f8d4d4b2b2b
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-rocm-py312-ubi9
PRODUCT=odh
RELEASE=3.6
