INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-ea.1-1778521486
PYLOCK_FLAVOR=cpu
PRODUCT=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-datascience-cpu-py312-rhel9
