INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9-test/simple/
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-ea.1-1777398804
PYLOCK_FLAVOR=cpu
LABEL_NAME=rhoai/odh-pipeline-runtime-datascience-cpu-py312-rhel9
LABEL_SUMMARY=Runtime data science notebook image for ODH notebooks
LABEL_DESCRIPTION=Runtime data science notebook image with base Python 3.12 builder image based on UBI9 for ODH notebooks
LABEL_DISPLAY_NAME=odh-pipeline-runtime-datascience-cpu-py312-rhel9
LABEL_K8S_DESCRIPTION=Runtime data science notebook image with base Python 3.12 builder image based on UBI9 for ODH notebooks
LABEL_COM_REDHAT_COMPONENT=odh-pipeline-runtime-datascience-cpu-py312-rhel9
LABEL_COM_REDHAT_LICENSE_TERMS=https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf
LABEL_AUTHORITATIVE_SOURCE_URL=
LABEL_BUILD_COMMIT_REF=
LABEL_BUILD_SOURCE_LOCATION=
LABEL_BUILD_IMAGE=
