# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.6.0-ea.1-1785513522@sha256:2e2a36eab9a91ee66d49453c5a8ce4f7678340b775f06366fea52a088ae72716
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-datascience-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
