#!/usr/bin/env bash
set -Eeuxo pipefail

# Our build tooling depends on requirements.txt files with hashes
# Namely, Konflux (https://konflux-ci.dev/), and Cachi2 (https://github.com/containerbuildsystem/cachi2).

# The following will create an extra requirement.txt file for every Pipfile.lock we have.
micropipenv --version || pip install "micropipenv==1.9.0"
uv --version || pip install "uv==0.8.12"
find . -name Pipfile.lock -execdir bash -c '
  pwd
  echo "# Generated by /scripts/sync-requirements-txt.sh from Pipfile.lock" > requirements.txt &&
  echo >> requirements.txt &&
  micropipenv requirements >> requirements.txt
  uv pip compile pyproject.toml --output-file pylock.toml --format pylock.toml --generate-hashes --emit-index-url --python-platform linux --no-annotate -q' \;
