#!/usr/bin/env bash
set -Eeuxo pipefail

# Our build tooling depends on requirements.txt files with hashes
# Namely, Konflux (https://konflux-ci.dev/), and Cachi2 (https://github.com/containerbuildsystem/cachi2).

# The following will create an extra requirement.txt file for every Pipfile.lock we have.
uv --version || pip install uv
cd jupyter
find . -name requirements.txt -execdir bash -c '
  full_path=$(pwd)

  echo "# Generated by /scripts/sync-requirements-txt.sh from uv.lock" > requirements.txt
  echo >> requirements.txt

  temp_dir="${full_path%/*}"
  image_name="${temp_dir##*/}"

  if [[ "$full_path" == *"/rocm/"* ]]; then
    image_name="${image_name}-rocm"
  fi

  uv export --format requirements-txt --group jupyter-${image_name}-image >> requirements.txt' \;
