# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.8:3.6.0-1789756857@sha256:84e928efbd8c3e4ca54a46a9d1f3406f9290204963f277b8bc19560b530117ae
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
