INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cuda12.9-ubi9/simple/
CPU_INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cpu-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.4.0-1774635920
PYLOCK_FLAVOR=cuda
