# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:on-pr-ada6d4b73c24698dda2882ee8119cf85b1a00912@sha256:15fd5086c45f1a87f273ad669098058213c5df8b6a5ffc310d1f12a0db2f6391
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.6
