# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.8:3.6.0-ea.2-1788562815@sha256:5fa6a07bc715a20d1d8561085bc9adb7f4feda62708e7e4a71ea4f1ee17d6fc8
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
