# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=registry.redhat.io/rhel9/python-312:9.6-1762373758@sha256:d350329565030871c36d24c43533db869e892390fb47dc5c44512a32792dc623
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-baseline-cpu-py312-ubi9
PRODUCT=odh
RELEASE=3.6
