# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.6.0-ea.1-1785868204@sha256:ea1146bf5a780606e07879efb7a3de1aee48037424799017f8774a3d41d83fea
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-baseline-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
