BASE_IMAGE_CPU=quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest
BASE_IMAGE_CUDA=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v13.0
BASE_IMAGE_ROCM=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:v7.1
PRODUCT=odh
RELEASE=3.5
LABEL_REGISTRY_PREFIX=opendatahub
