BASE_IMAGE_CPU=quay.io/aipcc/base-images/cpu:3.5.0-ea.2-1780972106
BASE_IMAGE_CUDA=quay.io/aipcc/base-images/cuda-13.0-el9.6:3.5.0-ea.2-1780972037
BASE_IMAGE_ROCM=quay.io/aipcc/base-images/rocm-7.1-el9.6:3.5.0-ea.2-1780597719
PRODUCT=rhoai
RELEASE=3.5
LABEL_REGISTRY_PREFIX=rhoai
