BASE_IMAGE=registry.access.redhat.com/ubi9/python-312:latest@sha256:a6e76c7e9def80d1b736d366c22ba88245d6ec86113b5b2655d52e0ba288b5db
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-universal-cpu-py312-ubi9
PRODUCT=odh
RELEASE=3.5
