BASE_IMAGE=registry.redhat.io/ubi9/python-312:9.8-1784177776
OC_IMAGE=registry.redhat.io/openshift4/ose-cli-rhel9:v4.18@sha256:6c071841ac15c8e9b24fff34334694006efcda8a0976cceeabd05bf98eb8c147
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-universal-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
