---
"name": "Build Notebooks (pr)"
"on":
  "pull_request":
    "paths-ignore":
      # Don't build images if the only thing that changed is image digests in manifests
      - manifests/base/params-latest.env
      - manifests/base/params.env
      # In fact, skip the build if there are only changes in manifests and nowhere else
      - manifests/**

permissions:
  contents: read
  packages: read
  pull-requests: read

concurrency:
  group: ${{ format('build-notebooks-pr-{0}', github.event.pull_request.number) }}
  cancel-in-progress: true

jobs:
  gen:
    name: Generate job matrix
    runs-on: ubuntu-latest
    # rhds/notebooks builds from quay.io/aipcc bases and requires pull_request_target trigger
    if: ${{ github.repository != 'red-hat-data-services/notebooks' }}
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
      has_jobs: ${{ steps.gen.outputs.has_jobs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false  # https://github.com/actions/checkout/issues/2312

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6.4.0
        with:
          go-version: "stable"
          cache-dependency-path: "scripts/buildinputs/go.mod"

      # RHAIENG-3914: use env vars to prevent GitHub Actions expression injection
      - name: Determine targets to build based on changed files
        run: |
          set -x
          git fetch --no-tags origin "pull/${PR_NUMBER}/head:${HEAD_REF}"
          git fetch --no-tags origin "+refs/heads/${BASE_REF}:refs/remotes/origin/${BASE_REF}"
          python3 ci/cached-builds/gen_gha_matrix_jobs.py \
            --from-ref "origin/${BASE_REF}" \
            --to-ref "${HEAD_REF}" \
            --rhel-images exclude \
            --s390x-images include
        id: gen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        shell: bash

  build:
    name: "${{ matrix.target }} · ${{ matrix.platform }}"
    needs: ["gen"]
    strategy:
      fail-fast: false
      matrix: "${{ fromJson(needs.gen.outputs.matrix) }}"
    uses: ./.github/workflows/build-notebooks-TEMPLATE.yaml
    if: ${{ fromJson(needs.gen.outputs.has_jobs) }}
    with:
      target: "${{ matrix.target }}"
      python: "${{ matrix.python }}"
      github: "${{ toJSON(github) }}"
      platform: "${{ matrix.platform }}"
      subscription: "${{ matrix.subscription }}"
    secrets: inherit
