---
name: Disconnected Readiness
"on":
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@6f7fc06230f5eeabfd134d819219314d54f0c7e7  # v1.0.0
    with:
      rules: ""
