---
name: Disconnected Readiness
"on":
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@bb546fe11d03b3a05dc5ad177a8ef27fe0c02f06  # v1.4.5
    with:
      rules: ""
