---
name: Disconnected Readiness
"on":
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@038f71519f7f14bb951f9d5cd2e9fa43ea74f848  # v1.4.6
    with:
      rules: ""
