---
"name": "Docs (release notes)"
"on":
  "push":
  "pull_request":
  "workflow_dispatch":

permissions:
  contents: read

env:
  poetry_version: '1.8.3'

jobs:
  generate-releasenotes:
    name: Generate list of images for release notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      # https://github.com/astral-sh/setup-uv
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
        with:
          version-file: uv.toml
          python-version: "3.14"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Run the release notes script
        run: |
          set -Eeuxo pipefail
          uv run ci/package_versions.py | tee ${GITHUB_STEP_SUMMARY}
