---
"name": "Docs (release notes)"
"on":
  "push":
    branches: [main, stable, 'rhoai-*']
  "pull_request":
  "workflow_dispatch":

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  poetry_version: '1.8.3'

jobs:
  generate-releasenotes:
    name: Generate list of images for release notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup uv and Python
        uses: ./.github/actions/setup-uv

      - name: Run the release notes script
        run: |
          set -Eeuxo pipefail
          uv run ci/package_versions.py | tee ${GITHUB_STEP_SUMMARY}
