---
"name": "Docs (release notes)"
"on":
  "push":
  "pull_request":
  "workflow_dispatch":

permissions:
  contents: read

env:
  poetry_version: '1.8.3'

jobs:
  generate-releasenotes:
    name: Generate list of images for release notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      # https://github.com/astral-sh/setup-uv
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          version-file: pyproject.toml
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: "3.14"

      - name: Run the release notes script
        run: |
          set -Eeuxo pipefail
          uv run ci/package_versions.py | tee ${GITHUB_STEP_SUMMARY}
