---
name: Post-Codefreeze Gatekeeper

"on":
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled]
    branches:
      - 'rhoai-3.5'

jobs:
  post-codefreeze-gate:
    if: github.event.action != 'labeled' || github.event.label.name == 'run-gatekeeper'
    permissions:
      issues: write
    uses: red-hat-data-services/devops-shared-resources/.github/workflows/post-codefreeze-gate-logic.yml@3a2cae1f65fcb1b35600d4083a87241f3660417b  # 3a2cae1
    secrets:
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
