# https://github.com/ruivieira/trustyai-explainability-python/blob/main/.github/workflows/security.yaml
---
name: Security
"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Trivy scan (fs)
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    steps:

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Trivy scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25  # v0.36.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'MEDIUM,HIGH,CRITICAL'
          exit-code: '0'
          ignore-unfixed: false

      - name: Update Security tab
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a  # v4.36.3
        with:
          sarif_file: 'trivy-results.sarif'
