# https://github.com/ruivieira/trustyai-explainability-python/blob/main/.github/workflows/security.yaml
---
name: Security
"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Trivy scan (fs)
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Trivy scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1  # v0.35.0
        with:
          scan-type: 'fs'
          trivy-config: trivy.yaml
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'

      - name: Update Security tab
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225  # v4.35.2
        with:
          sarif_file: 'trivy-results.sarif'
