---
name: Validation of software versions referenced in ImageStream manifests
on:  # yamllint disable-line rule:truthy
  push:
    # Since this check is so resource demanding, let's restrict also push action here.
    paths:
      - 'manifests/base/params.env'
      - 'manifests/base/*-imagestream.yaml'
      - 'ci/check-software-versions.py'
  pull_request:
    paths:
      - 'manifests/base/params.env'
      - 'manifests/base/*-imagestream.yaml'
      - 'ci/check-software-versions.py'
  workflow_dispatch:
  release:

permissions:
  contents: read

jobs:
  validation-of-sw-versions-in-imagestreams:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Prepare disk / Podman storage
        run: |
          set -Eeuxo pipefail
          df -h
          free -h

          # opendatahub-io/notebooks#3965; store rootful graphs under /mnt
          sudo mkdir -p /mnt/containers/storage
          sudo chown -R "${USER}:${USER}" /mnt/containers/storage
          sudo cp ci/cached-builds/storage.conf /etc/containers/storage.conf
          sudo mkdir -p /mnt/containers/storage/tmp
          # should reset storage when changing storage.conf
          sudo podman system reset --force

          # quick check that podman works
          sudo podman info

      - name: Check software versions in manifest referencing the images
        id: software-versions-check
        run: |
          sudo ./ci/check-software-versions.py --prune-podman-data
